name: rwkv_studio
description: "RWKV Studio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.6+7

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  rwkv_dart: ^1.1.6
  rwkv_downloader: ^1.0.2

  #  rwkv_libs:
  #    git:
  #      url: https://github.com/dengzii/rwkv_libs.git
  #      ref: dev

  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  dio: ^5.9.2
  rxdart: ^0.28.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  uuid: ^4.5.3

  detect_proxy_setting: ^0.0.9
  package_info_plus: ^10.1.0
  flutter_svg: ^2.2.4
  window_manager: ^0.5.1
  fluent_ui: ^4.15.1
  flutter_acrylic: ^1.1.4
  gpt_markdown: ^1.1.6
  vyuh_node_flow: ^0.27.3

  file_selector: ^1.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  desktop_drop: ^0.7.1
  crypto: ^3.0.7
  logging: ^1.3.0
  archive: ^4.0.9

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-VariableFont_wght.ttf

  assets:
    - assets/rwkv/
    - assets/img/
    - assets/config/
